runtime: python
env: flex
entrypoint: gunicorn -b :$PORT python_cloud_storage:wsgi

beta_settings:
    cloud_sql_instances: customer-management-288011:asia-south1:cust-asset

runtime_config:
  python_version: 3

handlers:
  - url: /static
    static_dir: static

 